// History Builder copy strings, HISTORY_BUILDER_SPEC section 11. BINDING and
// VERBATIM: consumed exactly as written in the spec. Do not rewrite, reflow,
// or add punctuation. No em dashes. No urgency vocabulary (urgent, critical,
// overdue, immediately) anywhere in this file.
export const HB_COPY = {
  "C-01": { title: "Add your current medications", sub: "Start with your anti-rejection medicines. Have your bottles handy." },
  "C-02": { text: "Is this your complete medication list?", yes: "Yes, this is everything", no: "Not yet" },
  "C-03": { title: "Add your allergies", sub: "Include reactions if you know them.", emptyButton: "I have no known allergies" },
  "C-04": { title: "Add your transplant details", sub: "Organ, date, and transplant center." },
  "C-05": { title: "Confirm your active conditions", sub: "What you are being treated for now." },
  "C-06": { title: "Add your care team", sub: "Include your transplant coordinator and their phone number." },
  "C-07": { text: "Add your transplant coordinator's number when you have it." },
  "C-08": { title: "Your Emergency Packet is ready", body: "It covers your transplant, medications, allergies, and care team. You can open, print, or share it any time." },
  "C-09a": { title: "Add your latest tacrolimus level", sub: "Type it in or add a photo of the lab report." },
  "C-09b": { title: "Add your last two or three tacrolimus results", sub: "Trends need more than one point." },
  "C-10": { title: "Add your most recent liver panel", sub: "A photo or PDF of the report works." },
  "C-11": { text: "You take {medication}. Add {condition} to your conditions?", add: "Add", no: "No" },
  "C-12": { text: "This document may include medications, labs, or providers. Want to review and add them?", review: "Review", notNow: "Not now" },
  "C-13": { text: "Document saved. You can add details from it manually any time." },
  "C-14": { button: "That covers it" },
  "C-15": { button: "Later" },
  "C-16": { suffix: "Useful before your {date} appointment." },
  "C-17a": { button: "Upload a PDF" },
  "C-17b": { button: "Add a photo" },
  "C-17c": { button: "Type it in" },
  "C-18": { title: "Upload your transplant discharge summary", sub: "One document covers most of your transplant story." },
  "C-19": { title: "Add anything major since your transplant", sub: "Rejection episodes, infections, hospital stays, big medication changes." },
  "C-20": { title: "Add important past history", sub: "Major surgeries, diagnoses, and hospital stays a new physician would need to know." },
  "C-21": { header: "Optional. Store older documents here. They stay searchable. Nothing here is required." },
  "C-22": { add: "Add", skip: "Skip" },
  "C-23": { text: "Last entered {n} days ago" },
  "C-24": { text: "{List name} confirmed by patient on {date}" },
  "C-25": { title: "Add schedules and refill dates", sub: "For the medications you already listed." },
  "C-26": { title: "Confirm your basic details", sub: "Name, date of birth, and emergency contact." },
  "C-27a": { suffix: "Needed for your appointment prep." },
  "C-27b": { suffix: "Needed for your Emergency Packet." },
  "C-27c": { suffix: "Needed for your Medication Report." },
  "C-27d": { suffix: "Needed for your Patient Profile." },
  "C-28": { title: "Which appointment are you preparing for?", sub: "Pick one or add it." },
};
