// ── WO_DASHBOARD_POLISH_02 item 5 (DEC-060, DEC-061): the shared report shell ─
// One shell, one button, one gate. Renders the documents under node with a
// localStorage shim (the shell reads the profile for its identity line) and
// pins the screens to the shared PrintButton and the preflight gate.
// Run: npm run test:print-shell

import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = (p) => join(__dirname, "..", "src", p);

class Storage {
  constructor() { this._m = new Map(); }
  getItem(k) { return this._m.has(k) ? this._m.get(k) : null; }
  setItem(k, v) { this._m.set(k, String(v)); }
  removeItem(k) { this._m.delete(k); }
  clear() { this._m.clear(); }
  key(i) { return [...this._m.keys()][i] ?? null; }
  get length() { return this._m.size; }
}
globalThis.Storage = Storage;
globalThis.localStorage = new Storage();
globalThis.window = globalThis;
globalThis.addEventListener = () => {};
globalThis.removeEventListener = () => {};

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log("PASS — " + m); } else { fail++; console.log("FAIL — " + m); } };
// No <script> and no on*= attribute inside a tag (escaped text such as
// "&lt;img onerror=…&gt;" is content, not a handler).
const clean = (html) => !/<script\b/i.test(html) && !/<[^>]*\son[a-z]+\s*=/i.test(html);

const { reportDocument, tableHtml, rowsHtml, fmtD } = await import("../src/lib/printShell.js");

// ── 1. The shell escapes what it receives as text and never ships scripts ────
{
  const html = reportDocument({ title: "T <script>x</script>", subtitle: "S & more", body: "<p>ok</p>", disclaimer: "D <b>", patient: false });
  ok(clean(html), "shell document: no <script>, no inline handlers (CSP, v1.49.1)");
  ok(html.includes("T &lt;script&gt;x&lt;/script&gt;"), "title escaped");
  ok(html.includes("S &amp; more") && html.includes("D &lt;b&gt;"), "subtitle and disclaimer escaped");
  ok(html.includes("<p>ok</p>"), "body is trusted HTML from the builder");
  ok(html.includes('alt="Insina Health"') && html.includes("Personal Health Record") && html.includes("Printed:"), "brand block: logo, document kind, printed date");
  ok(html.includes("This document was generated by Insina Health Personal Health Dashboard"), "footer line kept from the profile printout");
  ok(html.includes("<title>Insina Health: T &lt;script&gt;x&lt;/script&gt;</title>"), "document title carries the report name (the PDF filename)");
  ok(!html.includes("Age ") && !html.includes('class="who"'), "patient: false leaves the identity line out");
}
{
  localStorage.setItem("mi_profile_personal", JSON.stringify({ name: "Test <Patient>", dob: "1970-01-01" }));
  const { ageFromDob } = await import("../src/store.js");
  const html = reportDocument({ title: "X", body: "" });
  ok(html.includes("Test &lt;Patient&gt;") && html.includes(`Age ${ageFromDob("1970-01-01")}`), "identity line: escaped name, DOB, computed age");
}
{
  const t = tableHtml([{ label: "A", key: "a" }, { label: "N", get: r => r.n, num: true }], [{ a: "<x>", n: 5 }, { a: "", n: null }]);
  ok(t.includes("&lt;x&gt;") && t.includes('<td class="num">5</td>') && (t.match(/<td[^>]*>–<\/td>/g) || []).length === 2, "tableHtml escapes cells, right-aligns numbers, dashes empties");
  ok(tableHtml([{ label: "A", key: "a" }], []).includes("Nothing recorded."), "an empty table says so");
  const r = rowsHtml([["L", "<v>"], ["Empty", ""], ["Nil", null]]);
  ok(r.includes("&lt;v&gt;") && !r.includes("Empty") && !r.includes("Nil"), "rowsHtml escapes and skips empty values (UI-23)");
  ok(fmtD("") === "–" && fmtD("Sept 2025") === "Sept 2025" && fmtD("2026-09-07") !== "2026-09-07", "fmtD: dash for empty, typed text as is, ISO as a US date");
}

// ── 2. Patient Profile from the stores (DEC-060) ─────────────────────────────
{
  localStorage.setItem("mi_profile_personal", JSON.stringify({ name: "<img src=x onerror=alert(1)>", dob: "1970-01-01", blood: "O+" }));
  localStorage.setItem("mi_profile_insurance", JSON.stringify({ ins1: "Blue Plan", mid1: "M-1" }));
  localStorage.setItem("mi_conditions", JSON.stringify([{ name: "Liver Transplant (2023)", status: "active" }]));
  localStorage.setItem("mi_meds_full", JSON.stringify([{ name: "Tacrolimus", dose: "2 mg", frequency: "BID", status: "active" }]));
  localStorage.setItem("mi_allergies", JSON.stringify([{ name: "Penicillin", allergen: "Penicillin", reaction: "hives", severity: "severe" }]));
  localStorage.setItem("mi_cards", JSON.stringify([
    { id: "c1", label: "Insurance", front: "data:image/jpeg;base64,AAAA", back: "" },
    { id: "c2", label: 'ID "quoted"', front: "data:image/jpeg;base64,BBBB", back: "" },
  ]));
  localStorage.setItem("mi_readings", JSON.stringify([{ id: "w1", date: "2026-08-12", weight: "182" }]));
  localStorage.setItem("mi_records", JSON.stringify([
    { id: "r1", type: "Procedure", title: "Biopsy", date: "2025-01-02" },
    { id: "r2", type: "Imaging", title: "CT Abdomen", date: "2025-02-03" },
  ]));
  localStorage.setItem("mi_labs", JSON.stringify([{ name: "ALT", value: "40", unit: "U/L", date: "2026-08-01", flag: false }]));
  const { buildProfileHtml } = await import("../src/lib/printProfile.js");
  const html = buildProfileHtml();
  ok(clean(html) && !html.includes("<img src=x") && html.includes("&lt;img src=x onerror=alert(1)&gt;"), "patient-entered name is escaped: no XSS through the profile printout (AUDIT_SEC_02 F-01)");
  ok(html.includes("LIVER TRANSPLANT RECIPIENT") && !html.includes("ON IMMUNOSUPPRESSION"), "short-form transplant banner from the shared derivation");
  ok(html.includes("ALLERGIES: Penicillin"), "allergies line under the banner");
  ok(html.indexOf('class="notice"') < html.indexOf("Personal Health Record"), "notice sits in the left column before the brand block (v1.53.5)");
  ok(html.includes("182 lbs"), "weight comes from the newest Vitals reading");
  ok(html.includes("Biopsy") && html.includes("CT Abdomen"), "Procedure and Imaging records merge into Procedures and Diagnostics");
  ok(html.includes("Blue Plan") && html.includes("Recent Lab Results") && html.includes("ALT"), "insurance and featured labs sections");
  ok(html.includes("<h2>Insurance &amp; ID Cards</h2>") && html.includes('src="data:image/jpeg;base64,AAAA"') && html.includes('src="data:image/jpeg;base64,BBBB"') && html.includes("ID &quot;quoted&quot;"),
     "every stored card prints by default, labels escaped (DEC-060)");
  const one = buildProfileHtml({ cardIds: ["c1"] });
  ok(one.includes("AAAA") && !one.includes("BBBB"), "cardIds narrows the cards section (the screen's picker)");
  localStorage.setItem("mi_cards", "[]");
  ok(!buildProfileHtml().includes("ID Cards"), "no cards, no cards section");
  localStorage.setItem("mi_allergies", "[]");
  ok(buildProfileHtml().includes("ALLERGIES: No allergies recorded"), "empty allergies are stated, never silent");
}

// ── 3. Screen reports ────────────────────────────────────────────────────────
{
  const b = await import("../src/lib/printReports.js");
  const v = reportDocument(b.buildVitalsReport([
    { date: "2026-09-01", time: "08:00", bp_s: 120, bp_d: 80, hr: 70, weight: 180, temp: 98.6, o2: 97, flag: true },
    { date: "2026-09-02", bp: "130/85" },
  ]));
  ok(v.includes("120/80") && v.includes("130/85") && v.includes("180 lb") && v.includes("97%") && v.includes("Flagged"), "vitals: BP from parts or text, units, flag");
  ok(v.indexOf("130/85") < v.indexOf("120/80"), "vitals newest first");
  const d = reportDocument(b.buildDocumentsReport([{ title: "<b>Doc</b>", category: "Labs", date: "2026-01-01", tags: ["a", "b"], isRef: true }]));
  ok(d.includes("&lt;b&gt;Doc&lt;/b&gt;") && d.includes("a, b") && d.includes("Reference"), "documents: escaped titles, joined tags, reference tag");
  const n = reportDocument(b.buildNotesReport([
    { title: "Visit", date: "2026-05-05", sections: [{ header: "Plan", body: "line1\nline2" }, { type: "checklist", items: [{ text: "Ask <q>", done: true }] }] },
    { title: "Legacy", content: "old & text", pinned: true },
  ]));
  ok(n.indexOf("Legacy") < n.indexOf("Visit"), "notes: pinned first");
  ok(n.includes("☑ Ask &lt;q&gt;") && n.includes("old &amp; text") && n.includes("<h3>Plan</h3>"), "notes: sections, checklists, and legacy content, escaped");
  const c = reportDocument(b.buildConditionsReport([{ name: "B", status: "resolved" }, { name: "A", status: "active", icd: "K76" }]));
  ok(c.indexOf("<strong>A</strong>") < c.indexOf("<strong>B</strong>") && c.includes("K76") && c.includes("1 active"), "conditions: active first, ICD tag, counts");
  const p = reportDocument(b.buildProceduresReport([{ procedure: "Biopsy", date: "2025-01-01", cpt: "47000", fromRecords: true }]));
  ok(p.includes("Biopsy") && p.includes("CPT 47000") && p.includes("from Records"), "procedures: codes and the record tag");
  const g = reportDocument(b.buildDiagnosticsReport([{ name: "CT", date: "2025-01-01", impression: "No acute <finding>" }]));
  ok(g.includes("No acute &lt;finding&gt;"), "diagnostics: impression escaped");
  const l = reportDocument(b.buildLabEntries([{ name: "ALT", value: "40", unit: "U/L", date: "2026-08-01", flag: true }]));
  ok(l.includes("Flagged") && l.includes("ALT") && l.includes("1 result recorded"), "lab entries: flag and count");
  ok([v, d, n, c, p, g, l].every(clean), "every screen report is script-free");
}

// ── 4. The Medication Report on the shell (content unchanged) ────────────────
{
  const { buildMedicationList } = await import("../src/lib/printMedicationList.js");
  const html = reportDocument(buildMedicationList([
    { name: "Tacrolimus <b>", brand: "Prograf", category: "Immunosuppressant", dose: "2 mg", frequency: "BID", status: "active", flag: true, refillDate: "2026-09-20" },
    { name: "Old", status: "inactive" },
  ]));
  ok(html.includes("Tacrolimus &lt;b&gt;") && html.includes("Prograf") && html.includes("REVIEW") && !html.includes("<strong>Old</strong>") && html.includes("<h3>Immunosuppressant</h3>"),
     "medication list: grouped by category, escaped, inactive excluded, review badge");
  ok(html.includes("Always confirm medications and dosages"), "medication list disclaimer kept");
}

// ── 5. One button, one gate (source pins) ────────────────────────────────────
{
  const btn = readFileSync(SRC("components/PrintButton.jsx"), "utf8");
  ok(btn.includes('import { requestReport } from "../rie/preflightChecks.js"') && btn.includes("requestReport(type"), "PrintButton runs every print through the RIE preflight (DEC-061 C)");
  const tabs = readdirSync(SRC("components/tabs")).filter(f => f.endsWith(".jsx"));
  const read = (f) => readFileSync(SRC("components/tabs/" + f), "utf8");
  const users = tabs.filter(f => read(f).includes("<PrintButton"));
  const expected = ["Tab02.jsx", "Tab04.jsx", "Tab05.jsx", "Tab06.jsx", "Tab09.jsx", "Tab10.jsx", "Tab12.jsx", "Tab14.jsx", "Tab15.jsx", "Tab16.jsx", "Tab17.jsx"];
  ok(expected.every(f => users.includes(f)), `every printing screen uses the shared PrintButton (got ${users.join(", ")})`);
  // Tab13's consent reprint keeps its own button: the consent record is outside DEC-061 by design.
  ok(!tabs.filter(f => f !== "Tab13.jsx").some(f => /<PrintLabel/.test(read(f))), "no screen (other than the consent reprint) renders the old PrintLabel button any more");
  const types = new Set();
  for (const f of tabs) for (const m of read(f).matchAll(/reportType[:=]\s*"([a-zA-Z]+)"/g)) types.add(m[1]);
  const reports = readFileSync(SRC("components/dashboard/ReportsPage.jsx"), "utf8");
  for (const m of reports.matchAll(/requestReport\("([a-zA-Z]+)"/g)) types.add(m[1]);
  const labelsSrc = readFileSync(SRC("rie/preflightChecks.js"), "utf8");
  const labels = labelsSrc.slice(labelsSrc.indexOf("export const REPORT_LABELS"), labelsSrc.indexOf("};", labelsSrc.indexOf("export const REPORT_LABELS")));
  const missing = [...types].filter(t => !new RegExp(`\\b${t}:`).test(labels));
  ok(types.size >= 10 && missing.length === 0, `every report type has a preflight label (${[...types].sort().join(", ")}${missing.length ? "; missing " + missing.join(", ") : ""})`);
  ok((reports.match(/requestReport\(/g) || []).length === 4 && reports.includes('requestReport("profile", () => printProfile())') && reports.includes('requestReport("edPrep", () => printEmergency())') && reports.includes('requestReport("labs", () => printLabReport(readLabs()))'),
     "Reports: the four prints are gated; the profile prints in one step with every card (DEC-060); the Emergency Card runs the ED Prep checklist; the Lab Report prints from the record");
}

// ── 6. The Lab Results Report from the library (Reports and the Labs screen share it) ──
{
  const { buildLabReport, labOutOfRange, parseRefRange } = await import("../src/lib/labReport.js");
  localStorage.setItem("mi_lab_custom_ranges", JSON.stringify({ creatinine: { low: 0.8, high: 1.2 } }));
  localStorage.setItem("mi_lab_category_order", JSON.stringify(["Chemistry", "CBC / Hematology"]));
  const html = reportDocument(buildLabReport([
    { name: "Creatinine", value: "1.4", unit: "mg/dL", refRange: "0.7-1.3", date: "2026-08-01", category: "Chemistry" },
    { name: "Creatinine", value: "1.1", unit: "mg/dL", refRange: "0.7-1.3", date: "2026-05-01", category: "Chemistry" },
    { name: "Platelets", value: "180", unit: "K/uL", refRange: "150-400", date: "2026-08-01", category: "CBC / Hematology" },
    { name: "<b>ALT</b>", value: "40", unit: "U/L", refRange: "7-56", date: "2026-08-01", category: "Liver Panel" },
  ]));
  ok(html.includes("Lab Results Report") && html.includes("3 tests") && (html.match(/<td>1\.4<\/td>|>1\.4</g) || []).length >= 1 && !html.includes(">1.1<"), "one row per test, the most recent value (A-04)");
  ok(html.includes("Flagged") && html.includes("(your range)") && html.includes("0.8–1.2"), "the doctor's range wins and flags the value");
  ok((html.match(/class="cat-hdr"/g) || []).length === 3, "one category header per category present");
  ok(html.indexOf("Chemistry") < html.indexOf("CBC / Hematology") && html.indexOf("CBC / Hematology") < html.indexOf("Liver Panel"), "categories follow the patient's saved order, then the rest");
  ok(html.includes("&lt;b&gt;ALT&lt;/b&gt;") && clean(html), "lab names are escaped; the document is script-free");
  ok(reportDocument(buildLabReport([])).includes("No lab results recorded yet"), "an empty record prints an honest empty state");
  ok(labOutOfRange({ name: "Sodium", value: "150", refRange: "135-145" }, {}) === true && parseRefRange("< 10.0").high === 10, "range helpers moved intact");
  const tab05 = readFileSync(SRC("components/tabs/Tab05.jsx"), "utf8");
  ok(tab05.includes('from "../../lib/labReport.js"') && !tab05.includes("function printLabReport(") && !tab05.includes("function labOutOfRange("), "the Labs screen imports the shared helpers instead of carrying its own copy");
}

console.log(`\n${pass} passed, ${fail} failed (print-shell)`);
assert.equal(fail, 0);
